Disease/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView
from django.conf import settings
from django.conf.urls.static import static
from . import *

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('', include('chat.urls')),
    path('appointment/', include('appointment.urls')),
    path('jet/', include('jet.urls')),
    path('jet/dashboard/', include('jet.dashboard.urls', 'jet-dashboard')),
    path('admin/', admin.site.urls),
    path('api/',include('api.urls')),
    path('doctor/',include('doctor.urls')),
    path('roleadmin/',include('roleadmin.urls')),
    path('patient/',include('patient.urls')),
    path('health/',include('Health.urls')),
    path('', RedirectView.as_view(url="health/")),
]
urlpatterns=urlpatterns+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)



admin.site.site_header = 'Smart Health'                    # default: "Django Administration"
admin.site.index_title = 'Features area'                 # default: "Site administration"
admin.site.site_title = 'HTML title from adminsitration' # default: "Django site admin"

api/urls.py
from django.contrib import admin
from django.urls import path ,include
from django.conf.urls import url
from django.views.generic.base import RedirectView
from rest_framework import routers
from api import views

router=routers.DefaultRouter()

router.register(r'api', views.DiseaseViewSet)
#router.register(r'auth', views.UserViewSet)

urlpatterns=[
    path(r'api/', include(router.urls)),
    path('',RedirectView.as_view(url="api/"))
]

patient/urls.py
from django.contrib import admin
from django.urls import path,include
from patient import views
from django.views.generic.base import RedirectView

1
urlpatterns = [   
path('chat/',views.chat,name="chat"),
path('patient/',RedirectView.as_view(url='patient_login/')),
path('patient_login/', views.patient_login,name='patient_login'),
path('patient_register/', views.patient_register,name='patient_register'),
path('patient_profile/',views.patient_profile,name='patient_profile'),
path('my_profile/',views.my_profile,name="my_profile"),

# path('form/', views.form, name="form"),

path('search_doctor/', views.search_doctor,name="search_doctor"),
path('search_doctor/doctor_profile/<int:pk>',views.doctor_profile),
#path('update_profile/',views.patient_update,name='update_profile'),
path('dashboard/', views.dashboard, name="dashboard"),

path('home/',views.home,name="home"),
path('home/doctor_profile/<int:pk>',views.doctor_profile),
path('feedback/',views.feedback,name="feedback"),
path('feedback/detail/<int:pk>',views.feedback_detail),
path('feedback/edit/<int:pk>',views.feedback_edit),
path('feedback/add_feedback',views.feedback_add),
path('feedback/delete/<int:pk>',views.feedback_delete),
path('view_appointment/',views.view_appointment,name="view_appointment"),
path('patient_appointment/',views.patient_appointment,name="patient_appointment"),
path('view_appointment/take/<int:pk>',views.take_appointment),
path('patient_appointment/cancel/<int:pk>',views.cancel_appointment),
path('patient_appointment/details/<int:pk>',views.details_appointment),
path('patient_appointment/details/<int:pk>/export_pdf',views.export_pdf),

# details/{{appointment.id}}
# path('check/', views.check, name="check"),
path('logoutpatient/', views.logoutpatient, name="logoutpatient"),

path('heart/', views.heart, name="heart"),
path('diabetes/', views.diabetes, name="diabetes"),

path('showimage/', views.showimage, name="showimage"),

]

patient/models.py
from django.db import models
from django.core.validators import MinLengthValidator, RegexValidator
from django.db.models import CASCADE
from django.contrib.auth.models import User
#from patient.models import PatientInfo
from django.db.models.signals import post_save
from django.db.models import signals
from django.dispatch import receiver
from doctor.models import *

# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    name=models.CharField(max_length=20)
    phone_regex = RegexValidator(regex=r'^\+?1?\d{9,15}$', message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.")
    phone_number = models.CharField(validators=[phone_regex], max_length=17, blank=True) # validators should be a list
    address=models.CharField(max_length=40)
    gender=models.CharField( max_length=50,blank=True,choices=(('Female','Female'),('Male','Male'),('Other','Other')))
    age=models.IntegerField(blank=True , null=True)
    status=models.CharField(max_length=20,blank=True,choices=(('Single','Single'),('Married','Married')))
    profile_pic=models.ImageField(blank=True,null=True)

    def __str__(self):
        return self.name

@receiver(post_save,sender=User)
def create_user_profile(sender,instance,created,**kwargs):
	if created:
		Profile.objects.create(user=instance,name=instance.username)


@receiver(post_save,sender=User)
def save_user_profile(sender,instance,**kwargs):
	instance.profile.save()

# when profile is deleted user is also delete
def delete_user(sender, instance=None, **kwargs):
    try:
        instance.user
    except User.DoesNotExist:
        pass
    else:
        instance.user.delete()
signals.post_delete.connect(delete_user, sender=Profile)

class Feedback(models.Model):
    text=models.TextField(max_length=200)
    title=models.CharField(max_length=50)
    date=models.DateTimeField(auto_now_add=True)
    uploaded_by=models.ForeignKey(Profile,on_delete=models.CASCADE)
    def __str__(self):
        return self.title

class WhoPredictDisease(models.Model):
    predict_by=models.ForeignKey(Profile,on_delete=models.CASCADE)
    predicted_disease=models.CharField(max_length=30)

    def __str__(self):
        return self.predicted_disease
   

class Disease1(models.Model):
    name=models.CharField(max_length=200)
    doctor=models.ForeignKey(DoctorInfo,on_delete=models.CASCADE,null=True)
    def __str__(self):
        return self.name 

# Create your models here.
class Heart(models.Model):
    age=models.IntegerField()
    sex=models.IntegerField()
    cp=models.IntegerField()
    trestbps=models.IntegerField()
    chol=models.IntegerField()
    fbs=models.IntegerField()
    restecg=models.IntegerField()
    thalach=models.IntegerField()
    exang=models.IntegerField()
    oldpeak=models.IntegerField()
    slope=models.IntegerField()
    ca	=models.IntegerField()
    thal=models.IntegerField()
    def to_dict(self):
        return{
            'age':self.age,
            'sex':self.sex,
            'cp':self.cp,
            'trestbps':self.trestbps,
            'chol':self.chol,
            'fbs':self.fbs,
            'restecg':self.restecg,
            'thalach':self.thalach,
            'exang':self.exang,
            'slope':self.slope,
            'oldpeak':self.oldpeak,
            'ca':self.ca,
            'thal':self.thal,

        }

class Diabetes(models.Model):
    Pregnancies=models.IntegerField()
    Glucose=models.IntegerField()
    BloodPressure=models.IntegerField()
    SkinThickness=models.IntegerField()
    Insulin=models.IntegerField()
    BMI=models.IntegerField()
    DiabetesPedigreeFunction=models.IntegerField()
    Age=models.IntegerField()
    
    def to_dict(self):
        return{
            'Pregnancies':self.Pregnancies,
            'Glucose':self.Glucose,
            'BloodPressure':self.BloodPressure,
            'SkinThickness':self.SkinThickness,
            'Insulin':self.Insulin,
            'BMI':self.BMI,
            'DiabetesPedigreeFunction':self.DiabetesPedigreeFunction,
            'Age':self.Age,
        }

class Image(models.Model):
    
    imagefile= models.FileField(upload_to='images/')

class ImageBlock(models.Model):
    imageblock = models.FileField(upload_to='images/')
  
    

patient/views.py
from django.shortcuts import render, redirect
from patient.forms import *
from django.contrib.auth import authenticate, logout,login
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from patient.models import Profile
from django.db import transaction
from patient.models import *
from chat import *
from chat.models import *
from chat.views import *

# output file to pdf
from django.shortcuts import HttpResponse
from django.template.loader import render_to_string

from weasyprint import HTML
import tempfile

# decorators

from patient.patient_decorators import unauthenticated_patient,allowed_users

from django.shortcuts import render, HttpResponse
import requests

from Health.forms import *
from api.models import Disease
from api import diseaseml

from patient.heart import pred_heart
from patient.image_block import predImageBlock
from patient.Diabetes import pred_diabetes
from patient.pneumonia import pred1
from api.diseaseml import pred
from .models import Image
from django.contrib.auth.models import Group

from django.db.models import Q
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from appointment.models import AppointmentDetails,BookedAppointment
from appointment.forms import BookedAppointmentForm

from django.db.models.functions import Concat
from django.db.models import Value


#For Pnemonia check
@login_required(login_url='patient_login')
@allowed_users(allowed_roles=['PATIENT'])
def showimage(request): 
    form= BlockImageForm(request.POST, request.FILES)


    if form.is_valid():
        form.save()
        lastimage = ImageBlock.objects.latest('id')
        imagefile = lastimage.imageblock
        result = predImageBlock(imagefile)


        if result[0][0] >= 0.5:

            #For pnenumonia prediction

            result=pred1(imagefile)
        
            context={}
            if result[0][0] == 1:
                prediction = 'You are suffering from pneumonia'
                disease_name="Pneumonia"
                # saving  user information who predict pneumonia and suggesting doctors
                predict=WhoPredictDisease(predict_by=request.user.profile,predicted_disease=disease_name)
                predict.save()
                disease=Disease1.objects.filter(name__icontains=disease_name)
                listDoctorID=[]
                for d in disease:
                    listDoctorID.append(d.doctor.id)
                disease_doctor_list=DoctorInfo.objects.filter(Q(id__in=listDoctorID))
                context= {
                'imagefile':imagefile,
                'form': form,
                'sur':prediction,
                'disease_doctor_list':disease_doctor_list,
                }
                return render(request, 'patient/image.html', context)
            else:
                prediction = "Your health is Normal."
                context= {
                'imagefile':imagefile,
                'form': form,
                'sur':prediction,
                }        
                return render(request, 'patient/image.html', context)

        else:   
            prediction = "You can not upload this image"
            contex = {'sur': prediction}
            return render(request, 'patient/image.html', contex)
    if request.method == "GET":
        sur = ' '
        imagefile = ''
        context= {
            'imagefile':imagefile,
            'form': form,
            'sur':sur,
            }
        return render(request, 'patient/image.html', context)
    
    
@login_required(login_url='patient_login')
@allowed_users(allowed_roles=['PATIENT'])
def diabetes(request):

    if request.method == "GET":
        diabetes_form=DiabetesForm()
        contex={
            'diabetes_form':diabetes_form
        }
        return render(request,'patient/diabetes.html', contex)


    elif  request.method=="POST":
        
        diabetes_form=DiabetesForm(request.POST)
        if diabetes_form.is_valid:
            diabetes_form.save()
            from patient.models import Diabetes
            ob = Diabetes.objects.latest('id')

            sur=pred_diabetes(ob)
            
           

            sur=", ".join( repr(e) for e in sur).strip("''")
          
            
            if sur== '1':
                context = {}
                result= "Yes, You are suffering  from Diabetes disease"
                predicted_disease_name="Diabetes"
                predict=WhoPredictDisease(predict_by=request.user.profile,predicted_disease=predicted_disease_name)
                predict.save()
                disease=Disease1.objects.filter(name__icontains=predicted_disease_name)
                listDoctorID=[]
                for d in disease:
                    listDoctorID.append(d.doctor.id)
                disease_doctor_list=DoctorInfo.objects.filter(Q(id__in=listDoctorID))
                
                context={
                    'sur': result,
                    'disease_doctor_list':disease_doctor_list,
                }
                return render(request,'patient/diabetes_results.html', context)

            elif sur=='0':
                context = {}
                context={'sur':'You are not suffering from diabetes disease',}
                return render(request,'patient/diabetes_results.html', context)



@login_required(login_url='patient_login')
@allowed_users(allowed_roles=['PATIENT'])
def heart(request):
    if request.method=="GET":
        heart_form=HeartForm()
        contex={
            'heart_form':heart_form
        }
        return render(request,'patient/heart.html', contex)
    if request.method =="POST":
        contex = {}
        if request.POST.get('age'):
            heart = Heart()

            age = request.POST.get('age')
        
            
            sex = request.POST.get('sex')
            sex = sex.lower()
            if sex == 'male':
                sex = 1
            elif sex == 'female':
                sex = 0
            elif sex == 'other':
                sex = 0.5
            
            cp = request.POST.get('cp')
            cp = cp.lower()
            if cp == "typical angina":
                cp = 0
            elif cp == "atypical angina":
                cp = 1
            elif cp == "non-anginal pain":
                cp = 2
            elif cp == 'asymptomatic':
                cp == 3

            
            trestbps = request.POST.get('trestbps')
            
            chol = request.POST.get('chol')
            
            fbs = request.POST.get('fbs')
            fbs = fbs.lower()
            if fbs == 'true':
                fbs = 1
            elif fbs == 'false':
                fbs = 0

            restecg = request.POST.get('restecg')
            restecg = restecg.lower()
            if restecg == "normal":
                restecg = 0
            elif restecg == "having st-t":
                restecg = 1
            elif restecg == 'hypertrophy':
                restecg = 2

            thalach = request.POST.get('thalach')
        

            exang = request.POST.get('exang')
            exang = exang.lower()

            if exang== 'yes':
                exang = 1
            elif exang == 'no':
                exang = 0
            oldpeak = request.POST.get('oldpeak')
            slope = request.POST.get('slope')
            slope = slope.lower()
            if slope =='upsloping':
                slope = 0
            elif slope == 'flat':
                slope = 1
            elif slope=='downsloping':
                slope =2

            ca = request.POST.get('ca')

            thal = request.POST.get('thal')
            thal = thal.lower()

            if thal =="normal":
                thal = 0
            elif thal == 'fixed defect':
                thal = 1
            elif thal =="reversable defect":
                thal = 2


            heart.age = age
            heart.sex = sex
            heart.cp = cp
            heart.chol = chol
            heart.trestbps = trestbps
            heart.fbs = fbs
            heart.restecg = restecg
            heart.thalach = thalach
            heart.exang = exang
            heart.oldpeak = oldpeak
            heart.slope = slope
            heart.ca = ca
            heart.thal = thal
    
            heart.save()

            ob=Heart.objects.latest('id')
            sur=pred_heart(ob)
            sur=", ".join( repr(e) for e in sur).strip("''")
            context={}
            if sur== '1':
                
                name= "Yes, You are suffuring from heart problems"
                predicted_disease_name="Heart"
                predict=WhoPredictDisease(predict_by=request.user.profile,predicted_disease=predicted_disease_name)
                predict.save()
                disease=Disease1.objects.filter(name__icontains=predicted_disease_name)
                listDoctorID=[]
                for d in disease:
                    listDoctorID.append(d.doctor.id)
                disease_doctor_list=DoctorInfo.objects.filter(Q(id__in=listDoctorID))
                context={
                    'sur':name,
                    'disease_doctor_list':disease_doctor_list
                }
            elif sur=='0':
                name="You are not suffuring from heart disease"
                context={
                    'sur':name,
                }
            
            return render(request,'patient/heart_results.html', context)
            

@login_required(login_url='patient_login')
@allowed_users(allowed_roles=['PATIENT'])
def dashboard(request):
    if request.method =="POST":
        contex = {}
        if request.POST.get('value1'):
            disease = Disease()
            value1 = request.POST.get('value1')
            
            value2 = request.POST.get('value2')
            
            value3 = request.POST.get('value3')
            

patient/templates/patient/appointment_detail.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block body_content %}
<div class="page-wrapper">
<div class="content"> 
    <div class="row">
            <h4 class="page-title" style="text-align: center;">E HEALTH CARE</h4>
    </div>

        <div class="row">
            <div class="col-md-6">
                <div class="project-info-box mt-0">
                    <h5>APPOINTMENT DETAILS</h5>
                    <hr/>
                    
                    <p><b>Appointment ID:</b><b>{{a.appointment_id.id}}</b></p>
                    <p><b>PATIENT NAME:</b>{{a.booked_by.name}}</p>
                    <p><b>CONTACT NUMBER:</b>{{a.booked_by.phone_number}}</p>
                    <p><b>EMAIL:</b>{{a.booked_by.user.email}}</p>
                    <p class="mb-0"><b>ADDRESS:</b>{{a.booked_by.address}}</p>
                </div>
                <hr/>
                <div class="project-info-box">
                    <p><b>DOCTOR NAME:</b>{{a.appointment_id.create_by.user.first_name}} {{a.appointment_id.create_by.user.last_name}}</p>
                    <p><b>APPOINTMENT DATE:</b>{{a.appointment_id.appointment_date|date:"M d, Y"}}</p>
                    <p><b>APPOINTMENT DAY:</b>{{a.appointment_id.appointment_day}}</p>
                    <p><b>AVAILABLE TIME:</b>{{a.appointment_id.appointment_start_time}}-{{a.appointment_id.appointment_end_time}}</p>
                </div><!-- / project-info-box -->

            </br>
             
        <a href="{{a.id}}/export_pdf" class="btn btn-info btn-user ">Download</a>         
        
        <a href="{% url 'patient_appointment' %}" class="btn btn-secondary">View List</a>
    </div>
    </div>
</div>
</div>





{% endblock %}

patient/templates/patient/appointment_list.html
{% extends "base.html" %}
{% load static %}

{% block body_content %}

<div class="page-wrapper">
    <div class="content">
        <div class="row">
            <div class="col-sm-4 col-3">
                <h4 class="page-title"> Appointments</h4>
            </div>

            <div class="col-sm-8 col-9 text-right m-b-20">
            <form class="form-inline my-2 my-lg-0 float-right" method="GET" action="" style="text-align: right;">
                <!-- {% csrf_token %} -->
                <input  type="text" class="form-control mr-sm-2" value="{{ request.GET.term }}" name="term" placeholder="Doctor name">
                <!-- <input value={{request.POST.term}} name="term" class="form-control mr-sm-2" type="text" placeholder="Search by speciality" aria-label="Search"> -->
                <button class="btn btn-outline-primary my-2 my-sm-0" type="submit" value="submit">Search</button>
            </form>
            </div>
        </div>  

        <div class="row">
            <div class="col-md-12">
                <div class="table-responsive" style="max-height: 1000px; overflow-x: auto; overflow-y: auto;">
                    <table class="table table-border table-striped custom-table datatable mb-0">
                        <thead>
                            <tr>
                                <th>Appointment ID</th>
                                <th>Doctor Name</th>
                                <th>Appointment Date</th>
                                <th>Appointment Time</th>
                                <th>Appointment Day</th>
                                <th class="text-right">Action</th>
                            </tr>
                        </thead>
                        <tbody>                
                            {% for appointment in appointments %}
                            <tr>
                                <td>
                                    {{appointment.id}}
                                </td>
                                <td>{{appointment.create_by.user.first_name}} {{appointment.create_by.user.last_name}}</td>
                                <td>{{appointment.appointment_date|date:"M d, Y"}}</td>
                                <td>{{appointment.appointment_start_time}}-{{appointment.appointment_end_time}}</td>
                                <td>{{appointment.appointment_day}}</td>
                                <td class="text-right">
                                    {% if appointment.appointment_status == 0 %}
                                    <a class="btn btn-primary" href="take/{{appointment.id}}">Take Appoinment</a>
                                    {% else %}
                                    <button class="btn btn-danger">Already Booked</button>
                                    {% endif %}
                                    <!-- <div class="dropdown dropdown-action">
                                        <a href="#" class="action-icon dropdown-toggle" data-toggle="dropdown" aria-expanded="false"><i class="fa fa-ellipsis-v"></i></a>
                                        <div class="dropdown-menu dropdown-menu-right">
                                            <a class="dropdown-item" href="edit/{{appointment.id}}"><i class="fa fa-pencil m-r-5"></i> Edit</a>
                                            <a class="dropdown-item" data-toggle="tooltip" data-placement="top" title="Delete" href="delete/{{appointment.id}}" onclick="return confirm('Are you sure want to delete this appointment')">
                                                <i class="fa fa-trash-o m-r-5"></i> Delete</a>
                                        </div>
                                    </div> -->
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>


{% endblock %}

patient/templates/patient/predict.html
{% extends "base.html" %}
{% block body_content %}

<div class="page-wrapper" >
    <div class="content">
        <div class="row">
            <div class="col-sm-12">
                <h4 class="page-title">Results</h4>
            </div>
        </div>

<div class="card-box" style="background-color: skyblue;">
    <!-- <h4 class="mb-5"> You are suffering from  {{Disease}} </h4> -->
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
      <!-- <h4 class="page-title"><strong>You are suffering from {{Disease}}</strong></h4> -->
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
      <h5>Suggested doctor Information</h5>

      <div class="container">
        <div class="row">
          <div class=" col md-12">
           
              <table class="table table-light">
                <thead>
                  <tr>
                    <th scope="col">Name</th>
                    <th scope="col">Email</th>
                    <th scope="col">Phone Number</th>
                  </tr>
                </thead>
                <tbody>
                
                  <tr>
                    <th> {{ name }}</th>
                    <td>{{email}}</td>
                    <td>{{phone}}</td>
                  </tr>
                  </table>

</div>
</div>
</div>
{% endblock %}

patient/templates/patient/profile.html
{% extends "base.html" %}

{% block body_content %}
        <div class="page-wrapper">
            <div class="content">
                <div class="row">
                    <div class="col-sm-12">
                        <h4 class="page-title">Edit Profile</h4>
                    </div>
                </div>
                   
<form method="POST" action="" enctype="multipart/form-data">
  {% csrf_token %}
   <div class="card-box">
                       <h3 class="card-title">My Informations</h3>
  <div class="form-group">
    <label for="id_email">Email address</label>&nbsp &nbsp
    <input class="form-control" value="{{request.user.email}}"  name="email"
      maxlength="254" id="id_email">
      <span class="text-danger" >
        {{user_form.email.errors}}
</span>
  </div>
  <br />
  <div class="form-group"><label for="id_name">Name</label>&nbsp &nbsp <input type="text" value="{{request.user.profile.name}}" name="name"
      maxlength="20"  class="form-control">
      <span class="text-danger" >
        {{patient_profile.name.errors}}
</span>
    </div>

  <br />
  <div class="form-group"><label for="id_phone_number">Phone number</label> &nbsp &nbsp<input type="text"
      class="form-control" value="{{request.user.profile.phone_number}}" name="phone_number" maxlength="17">
      <span class="text-danger" >
        {{patient_profile.phone_number.errors}}
</span>  
  </div>
  <br />
  <div class="form-group"><label for="id_address">Address</label>&nbsp &nbsp <input
      value="{{request.user.profile.address}}" type="text" class="form-control" name="address" maxlength="40">
      <span class="text-danger" >
        {{patient_profile.address.errors}}
</span>  
  </div>
  <br />
  <div class="form-group"><label for="id_gender">Gender</label> &nbsp &nbsp<select class="form-control form-control-lg"
      value="{{request.user.profile.gender}}" name="gender" id="id_gender">\n <option readonly value="Female">Female
      </option>\n\n <option readonly value="Male" selected>Male</option>\n\n <option readonly value="Other">Other
      </option>\n\n</select>
      <span class="text-danger" >
        {{patient_profile.gender.errors}}
</span>
    </div>
  <br />
  <div class="form-group"><label for="id_age">Age</label> &nbsp &nbsp<input class="form-control" type="text" name="age"
      value="{{request.user.profile.age}}" maxlength="20">
      <span class="text-danger" >
        {{patient_profile.age.errors}}
</span> 
    </div>
  <br />
  <div class="form-group"><label for="id_status">Status</label> &nbsp &nbsp<select name="status" id="id_status"
      class="form-control form-control-lg">\n <option value="Single" selected>Single</option>\n\n <option
        value="Married">Married</option>\n\n</select>
      
        <span class="text-danger" >
          {{patient_profile.status.errors}}
  </span>
      </div><br />

  <div class="form-group"><label for="id_profile_pic">Profile Picture</label>
    <br />
    <br />
    <input class="form-control-file" type="file" name="profile_pic" accept="image/*"  value="{{request.user.profile.profile_pic}}">
    <span class="text-danger" >
      {{patient_profile.profile_pic.errors}}
</span>
  </div>
  <br />


  <button type="submit" class="btn btn-primary btn-user "> Update Profile</button>

  <br />
  
  </div>
 
      
</form>
</div>
</div>


<!--
<h4 class="mb-5">My Profile</h4>
<div align="center">
   {% if request.user.profile.profile_pic.url != '' %}
  <img src="{{request.user.profile.profile_pic.url}}" alt="Images" height="300px"/>
  {% else %} 
  <i class="fas fa-10x fa-user-circle"></i>
  {% endif %}
</div>
<div class="card-body">
</div>

-->
<!--


<div  class="card text-white bg-secondary mb-3" >
  <div class="card-body">
  <div class="card-group">
    <br />

<form method="POST" action="" enctype="multipart/form-data">
  {% csrf_token %}
  <div class="form-inline">
    <label for="id_email">Email address</label>&nbsp &nbsp
    <input class="form-control" value="{{request.user.email}}" style="width: 300px;" type="email" name="email"
      maxlength="254" id="id_email">
  </div>
  <br />
  <div class="form-inline"><label for="id_name">Name</label>&nbsp &nbsp <input type="text" value="{{request.user.profile.name}}" name="name"
      maxlength="20" required id="id_name" class="form-control"></div>

  <br />
  <div class="form-inline"><label for="id_phone_number">Phone number</label> &nbsp &nbsp<input type="text"
      class="form-control" value="{{request.user.profile.phone_number}}" name="phone_number" maxlength="17"
      id="id_phone_number"></div>
  <br />
  <div class="form-inline"><label for="id_address">Address</label>&nbsp &nbsp <input
      value="{{request.user.profile.address}}" type="text" class="form-control" name="address" maxlength="40" required
      id="id_address"></div>
  <br />
  <div class="form-inline"><label for="id_gender">Gender</label> &nbsp &nbsp<select class="form-control form-control-lg"
      value="{{request.user.profile.gender}}" name="gender" id="id_gender">\n <option readonly value="Female">Female
      </option>\n\n <option readonly value="Male" selected>Male</option>\n\n <option readonly value="Other">Other
      </option>\n\n</select></div>
  <br />
  <div class="form-inline"><label for="id_age">Age</label> &nbsp &nbsp<input class="form-control" type="text" name="age"
      value="{{request.user.profile.age}}" maxlength="20" required id="id_age"></div>
  <br />
  <div class="form-inline"><label for="id_status">Status</label> &nbsp &nbsp<select name="status" id="id_status"
      class="form-control form-control-lg">\n <option value="Single" selected>Single</option>\n\n <option
        value="Married">Married</option>\n\n</select></div><br />

  <div class="form-inline"><label for="id_profile_pic">Profile Picture</label>
    <br />
    <br />
    <input class="form-control-file" type="file" name="profile_pic" accept="image/*" id="id_profile_pic"></div>
  <br />
  <br />

  <button type="submit" class="btn btn-primary btn-user "> Update Profile</button>

  <br />
  <br />
</form>
</div>
  </div>
</div>

-->


{% endblock %}